### ISSUE TITLE
Env Vars (windows) problem // Does not wear Doom items

### ISSUE THREAD

**Issue by RhymeRone** [hiperesp/DragonFable-Private-Server#89]
Hello, when I wear the low level doom items at the entrance of the game and press close, it sends them to the main screen.

https://github.com/user-attachments/assets/622095ba-e7b4-4606-8883-83749ebf0c66

Sometimes an image like this occurs on the main screen.
![chrome_mVqtfFmylD](https://github.com/user-attachments/assets/231f8623-0c6d-48c7-ad63-bb6372df4179)

**Comment by hiperesp** [comment]
I tried reproducing the error in 3 environments:

- PHP 8.4 - Server 15.9.2 alpha  
- PHP 8.2 - Server 15.9.2 alpha  
- PHP 8.2 - Server 15.9.14 alpha (same as the example provided)  

All using item ID 2815, but the error did not occur for me.  

I don't believe this is an issue with the SWF files because, when clicking on "preview," the SWF is loaded and displayed correctly. Usually, these errors occur when we try to load a SWF file that doesn't exist (in that case, an error would occur when clicking on "preview") or when clicking on "equip," but not on the "close" button.  

A possible guess: since Ruffle is on a nightly build, there’s a small chance this error is related to the specific build of Ruffle.  

Can you test it in your browser? The browser version uses the latest ruffle also, but it worked for me.

**Comment by RhymeRone** [comment]
Hello, I tried it again, same problem but I found something. I think the error is not related to doom items. After entering the game, when I clicked on the bag and then pressed the close button, I caught a warning above, and then it entered the main screen.

https://github.com/user-attachments/assets/9423754a-a7c9-4b54-9c4f-b5c83827b358

![wmplayer_yyPqOwei5Q](https://github.com/user-attachments/assets/5be7a59b-4ba3-4240-a5e9-3004ee4c0063)

(Please notify Verlyrus!) This seems to be the problem, but I'm not sure what it is.

**Comment by hiperesp** [comment]
this is the default dragonfable error message "Please notify Verlyrus!"...
I will check what can cause this problem

**Comment by hiperesp** [comment]
I identified what causes this error.

When we open the inventory, this function is called:
![image](https://github.com/user-attachments/assets/cfc0e1cc-4d67-4f44-9269-b2224e3edf6f)

*The happy path:*
The line 3166 verify if the server returned any error to show to user.
The line 3170 verify if the server returned a empty inventory.
The line 3172 verify if the char inventory have more than 2 items
If the line 3166 is true, the script ends here.
If the line 3170 is true and 3172 is true, this error "Error 2. Please notify Verlyrus!"

*The bad path:*
If a instability occurs when this function is called, the line 3166 will be false, the line 3170 will be true and if the user has more than 2 items, the line 3172 will be true also and this error will be shown.

I think this problem is a instability, because when we choose a character at character screen, this same function is called.

Another thing what make me think this problem is instability is because the error at character selection screen.

**Comment by RhymeRone** [comment]
https://github.com/user-attachments/assets/7d09b3ff-d624-412c-b812-da48453b2ca2


Yes, as you said, when there are more than 2 items, it kicks you out of the game, but when it is limited to 2, there is no problem.

It will be a little strange, but will there be a problem if we make that number 2 200? 
(I wonder what causes this indecision?)

**Comment by hiperesp** [comment]
This code i mentioned is from the game source, i can patch it to remove this validation, but i think the problem is a instability, caused by other things...
Later, i'll get in touch with you to understand what's causing this instability, but it doesn't seem to be related to the context of this project, it's probably due to the environment (PHP settings, Apache settings, etc).

**Comment by hiperesp** [comment]
done!
